soos-io/soos-api-client

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/logging/SOOSLogger.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-11335
=> PA-11335 Added method to upload tool results

package-lock.json, package.json, src/utilities.ts
=> ensureEnumValue refactor

package-lock.json, package.json, src/enums.ts, src/logging/SOOSLogger.ts
fix log level enum and logging comparison
=> fix log level enum and logging comparison

.github/pull_request_template.md, .vscode/settings.json, README.md, package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts
**Ticket:** https://soos.atlassian.net/browse/PA-11951 package update
=> PA-11951 package update

package-lock.json, package.json, src/utilities.test.ts, src/utilities.ts, tsconfig.json
=> added verifyScanStatus util

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-7197 Use status issues object for counts
=> PA-7197 Use status issues object for counts

package-lock.json, package.json, src/enums.ts, src/services/AnalysisService.ts
=> Add new integration names

.github/workflows/soos-sca-analysis.yml, package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts, src/utilities.ts
=> Contemplate finished on update status, allow null issues

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/enums.ts, src/services/AnalysisService.ts
=> dependency clean up / update

package-lock.json, package.json, src/services/AnalysisArgumentParser.ts, src/services/AnalysisService.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12267
=> PA-12267 Added common File methods 

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts
=> add max files query params

package-lock.json, package.json, src/services/AnalysisService.ts
=> Fix glob import

package-lock.json, package.json, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12336 remove fail message
=> PA-12336 remove fail message

package-lock.json, package.json, src/constants.ts, src/services/AnalysisService.ts
always exclude soos glob pattern
=> always exclude soos glob pattern

package-lock.json, package.json, src/utilities.test.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12267 Scan status to Exit Codes
=> PA-12267 Scan status to Exit Codes

package-lock.json, package.json, src/utilities.test.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12367 Fix exit code
=> PA-12367 Fix exit code

package-lock.json, package.json, src/services/AnalysisArgumentParser.ts, src/utilities.test.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12267 Code standardization
=> PA-12267 Code standardization

package-lock.json, package.json, src/enums.ts
=> Fix log level enum

package-lock.json, package.json, src/services/AnalysisService.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12353 workingDirectory rather than source
=> PA-12353 workingDirectory rather than source

package-lock.json, package.json, src/enums.ts, src/services/AnalysisArgumentParser.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12245 all packagemanagers / allowMultiple on parse enum
=> PA-12245 all packagemanagers / allowMultiple on parse enum

package-lock.json, package.json, src/logging/SOOSLogger.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12401 Fix log level followup, override level on verbose
=> PA-12401 Fix log level followup, override level on verbose

README.md, package-lock.json, package.json, src/enums.ts, src/services/AnalysisArgumentParser.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12403 remove PASS/IGNORE
=> PA-12403 remove PASS/IGNORE

package-lock.json, package.json, src/services/AnalysisService.ts, src/utilities.test.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12431 have exit code function return message as well so we can repeat it in the output
=> PA-12431 have exit code func return message

.vscode/settings.json, package-lock.json, package.json, src/services/AnalysisService.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12369 change issue type output
=> PA-12369 change issue type output

package-lock.json, package.json, src/services/ContributorAuditArgumentParser.ts, src/services/ContributorAuditService/ContributorAuditService.ts
**Ticket:** https://soos.atlassian.net/browse/PA-11946 Audit script improvements
=> PA-11946 Audit script improvements

package-lock.json, package.json, src/services/AnalysisService.ts
- Retry on first complete status to ensure stats are updated
**Ticket:** https://soos.atlassian.net/browse/PA-12554
=> PA-12554 Retry on first completion for stats to be updated

package-lock.json, package.json, src/services/ArgumentParserBase.ts
=> Make addEnumArgument accessible from argparse base

.github/workflows/soos-sca-analysis.yml, package-lock.json, package.json, src/api/SOOSApiClient.ts
=> try, not tyy

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts
Including unknown package issues in results logging
**Ticket:** https://soos.atlassian.net/browse/PA-12369
=> PA-12369 Including unknown package issues in results logging

package-lock.json, package.json, src/services/AnalysisService.ts
Consolidate update scan triggers on SCA
=> Consolidate update scan triggers on SCA

.github/workflows/codeql-analysis.yml, package-lock.json, package.json, src/services/ContributorAuditArgumentParser.ts, src/services/ContributorAuditService/providers/BitbucketCloud/BitbucketCloudContributorAuditProvider.ts, src/services/ContributorAuditService/providers/GitHub/GitHubContributorAuditProvider.ts
**Ticket:** https://soos.atlassian.net/browse/PA-13070 Bitbucket cloud follow up clean-up
=> PA-13070 Bitbucket cloud follow up clean-up

package-lock.json, package.json, src/services/ContributorAuditService/providers/GitHub/GitHubApiClient.ts
**Ticket:** https://soos.atlassian.net/browse/PA-12839 Point to proper message property on github errors
=> PA-12839 Point to proper message property on github errors

package-lock.json, package.json, src/logging/SOOSLogger.ts
set verbose when log level is set to debug
https://soos.atlassian.net/browse/PA-13278
=> PA-13278 set verbose when log level is set to debug

package-lock.json, package.json, src/logging/SOOSLogger.ts, src/services/ContributorAuditService/providers/GitHub/GitHubApiClient.ts
=> PA-13286 Fix Pagination handler on github

package-lock.json, package.json, src/constants.ts, src/enums.ts, src/services/ContributorAuditArgumentParser.ts, src/services/ContributorAuditService/ContributorAuditService.ts
**Ticket:** https://soos.atlassian.net/browse/PA-13368
=> PA-13368 Add results as TXT for SCM Audit

.github/workflows/npm-publish-pre-release.yml, package-lock.json, package.json
=> Add pre release workflow

package-lock.json, package.json
add check/patch run scripts - extend keywords
=> add check/patch run scripts - extend keywords

package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts
- Code cleanup
- Fix bad API mapping
**Ticket:** https://soos.atlassian.net/browse/PA-14440
=> PA-14440 bug fixing and logging

.npmrc, package-lock.json, package.json, src/enums.ts
**Ticket:** https://soos.atlassian.net/browse/PA-14016 add unity/amazonLinux to package manager list
=> PA-14016 add package managers / package update

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts
- Including manifests with lock files if required
**Ticket:** https://soos.atlassian.net/browse/PA-14667
=> PA-14667 Including manifests with lock files if required

package-lock.json, package.json, src/enums.ts
=> add github to packagemanagers

package-lock.json, package.json, src/services/AnalysisService.ts
=> manifests can be null

.github/workflows/run-tests.yml, README.md, package-lock.json, package.json, src/api/SOOSApiClient.ts, src/logging/SOOSLogger.ts, src/services/ContributorAuditService/ContributorAuditService.ts, src/services/ContributorAuditService/providers/BitbucketCloud/BitbucketCloudApiClient.ts, src/services/ContributorAuditService/providers/BitbucketCloud/BitbucketCloudContributorAuditProvider.ts, src/services/ContributorAuditService/providers/GitHub/GitHubApiClient.ts, src/services/ContributorAuditService/providers/GitHub/GitHubContributorAuditProvider.ts
**Ticket:**
https://soos.atlassian.net/browse/PA-13048 package update (node 20 compat)
https://soos.atlassian.net/browse/PA-15137 remove verbose from logging
=> PA-13048 package update (node 20 compat) / PA-15137 remove verbose

package-lock.json, package.json, src/services/ArgumentParserBase.ts
**Ticket:** https://soos.atlassian.net/browse/PA-15137
=> PA-15137 deprecate verbose argument (functionality already removed)

.github/workflows/soos-sca-analysis.yml, package-lock.json, package.json, src/services/ArgumentParserBase.ts
action version to v2 / verbose warning
=> action version to v2 / verbose warning

package-lock.json, package.json, src/services/ArgumentParserBase.ts
=> call checkDeprecatedArguments

package-lock.json, package.json, src/services/AnalysisService.ts
Remove console dump of SARIF output
=> Remove console dump of SARIF output

package-lock.json, package.json, src/services/AnalysisService.ts
change "working directory" in log to "directory"
=> change "working directory" in log to "directory"

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts
Always include non-lock file if there is no corresponding lock file format
**Ticket:** https://soos.atlassian.net/browse/PA-16149
=> PA-16149 Always include non-lock file if there is no corresponding lock file format

package-lock.json, package.json, src/services/AnalysisService.ts
- Look for all contrib dev env vars across all ci/cd systems
**Ticket:** https://soos.atlassian.net/browse/PA-16351
=> PA-16351 look for all contrib dev env vars

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/api/SOOSAttributionApiClient.ts, src/enums.ts, src/services/AnalysisArgumentParser.ts, src/services/AnalysisService.ts, src/services/ArgumentParserBase.ts, src/utilities.ts
**Ticket:** https://soos.atlassian.net/browse/PA-15417
=> PA-15417 move to new attribution api endpoints

package.json, src/services/AnalysisService.ts, src/services/ArgumentParserBase.ts
- Improve export validation
- Fix output file formatting for non-json files
**Ticket:** https://soos.atlassian.net/browse/PA-15417
=> PA-15417/PA-16529 Improve export validation / Fix non-json output file formatting

package-lock.json, package.json, src/services/ArgumentParserBase.ts
=> package update

src/services/ArgumentParserBase.ts
**Ticket:** https://soos.atlassian.net/browse/PA-16531 Update validation messages
=> PA-16531 Update validation messages

package-lock.json, package.json, src/services/AnalysisArgumentParser.ts, src/services/ArgumentParserBase.ts
=> ignore unknown in enums

package-lock.json, package.json, src/utilities.test.ts, src/utilities.ts
=> use excluded list for display

package-lock.json, package.json, src/services/ArgumentParserBase.ts
SAST does not support CycloneDX
=> SAST does not support CycloneDX

package-lock.json, package.json, src/api/SOOSApiClient.ts, src/api/SOOSAttributionApiClient.ts, src/services/AnalysisService.ts
allow api client to skip response logging
=> allow api client to skip response logging

package-lock.json, package.json, src/enums.ts
- Added ManifestStatus.Duplicate enum value
**Ticket:** https://soos.atlassian.net/browse/PA-16671
=> PA-16671 Added ManifestStatus.Duplicate enum value

README.md, package-lock.json, package.json
package/readme update/add badges
=> package/readme update/add badges

package-lock.json, package.json, src/services/AnalysisService.ts
=> do not stringify json

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/api/SOOSApiClient.ts
don't log tool output request bodies
=> don't log tool output request bodies

package-lock.json, package.json
=> package update (cve updates)

package-lock.json, package.json, src/services/AnalysisArgumentParser.ts
package update / exclude default enums
=> package update / exclude default enums

package-lock.json, package.json, src/enums.ts, src/services/ArgumentParserBase.ts
adjust enum for integrationName
=> adjust enum for integrationName

package-lock.json, package.json, src/services/AnalysisService.ts
=> logging messages

package-lock.json, package.json, src/services/AnalysisArgumentParser.test.ts, src/services/ArgumentParserBase.ts
=> block empty when required

package-lock.json, package.json, src/constants.ts, src/services/AnalysisService.ts
- Remove utf8 encoding so we fallback on file encoding
**Ticket:** https://soos.atlassian.net/browse/PA-17196
=> PA-17196 Remove utf8 default encoding

package-lock.json, package.json, src/utilities.test.ts, src/utilities.ts
=> add obfuscateCommandLine util

package-lock.json, package.json, src/api/SOOSApiClient.ts, src/api/SOOSUserApiClient.ts
API call error handling updates
=> API call error handling updates

package-lock.json, package.json, src/api/SOOSApiClient.ts, src/utilities.ts
=> handle coded message models

package-lock.json, package.json, src/services/AnalysisArgumentParser.test.ts, src/utilities.test.ts
=> update tests /packages

package-lock.json, package.json, src/utilities.test.ts, src/utilities.ts
=> more obfuscation tests

package-lock.json, package.json, src/api/SOOSApiClient.ts
=> update 403 messaging

package-lock.json, package.json, src/api/SOOSApiClient.ts
check coded message before status only for error msg
=> check coded message before status only for error msg

package-lock.json, package.json, src/logging/SOOSLogger.test.ts, src/logging/SOOSLogger.ts
conditionally log logLineSeparator / clean up
=> conditionally log logLineSeparator / clean up

package-lock.json, package.json, src/api/SOOSHooksApiClient.ts
=> add numberOfCommits

package-lock.json, package.json, src/api/SOOSApiClient.ts
=> handle more 403 codes

package-lock.json, package.json
force  "brace-expansion": "2.0.1"
=> force  "brace-expansion": "2.0.1"

package-lock.json, package.json
=> "brace-expansion": "2.0.1"

package-lock.json, package.json
=> remove override

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts
add MaliciousPackage issue type
=> add MaliciousPackage issue type

package-lock.json, package.json, src/enums.ts, src/services/AnalysisService.ts
package update / remove none severity
=> package update / remove none severity

package-lock.json, package.json, src/constants.ts, src/services/AnalysisService.ts
=> add success color

package-lock.json, package.json, src/services/AnalysisService.ts
support optional base64 encoding on form data
=> support optional base64 encoding on form data

package-lock.json, package.json, src/services/AnalysisService.ts
expose shouldWarnOnNodeVersion
=> expose shouldWarnOnNodeVersion

package-lock.json, package.json, src/services/AnalysisService.ts, src/utilities.test.ts, src/utilities.ts
=> remove temp node flag

package-lock.json, package.json, src/api/SOOSApiClient.ts
=> check for WAF block

package-lock.json, package.json, src/services/AnalysisService.ts
=> hash logic

package-lock.json, package.json, src/services/AnalysisService.ts, src/utilities.ts
=> read bytes to base64 directly

knip.json, package-lock.json, package.json, src/services/AnalysisService.ts
update lock file / clean up reduce / add knip.json
=> update lock file / clean up reduce / add knip.json

package-lock.json, package.json, src/api/SOOSAnalysisApiClient.ts, src/services/AnalysisService.ts
- Fixed json model
- Updated error logging
**Tickets:** 
https://soos.atlassian.net/browse/PA-18876
https://soos.atlassian.net/browse/PA-18694
=> PA-18876 Fixed json model / PA-18694 Updated error logging
